- hosts: nodesactivemq
  tasks:
  
  - name: Liberando a porta no firewall - Máquina Node ActiveMQ
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
    - 8161
    - 61616
    - 5445 
    - 5672
    - 61613
    - 1883

  - name: Ativando firewall da máquina - Máquina Node ActiveMQ
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall já está ativado."
            else
            echo "Ativando firewall da máquina"
            yes | ufw enable
            ufw status
            fi

