- hosts: nodesback
  tasks:

  - name: Liberando range de portas 8000:8100 no firewall - Máquina Node Back
    ufw:
      rule: allow
      port: '8000:8100'
      proto: tcp  

  - name: Liberando range de portas 9600:9999 no firewall - Máquina Node Back
    ufw:
      rule: allow
      port: '9600:9999'
      proto: tcp

  - name: Liberando a porta no firewall - Máquina Node Back
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
    - 18520
    - 17852
    - 17853
    - 17589
    - 17969
    - 10001
    - 1485

  - name: Ativando firewall da máquina - Máquina Node Back
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall já está ativado."
            else
            echo "Ativando firewall da máquina"
            yes | ufw enable
            ufw status
            fi