- hosts: nodesnginx
  tasks:
  
  - name: Liberando a porta no firewall - Node Nginx
    ufw:
      rule: allow
      port: ''
      proto: tcp

  - name: Ativando firewall da m치quina - Node Nginx
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi


