- hosts: nodespatroni
  tasks:
  
  - name: Liberando a porta no firewall - Node Patroni
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop: 
    - 5432
    - 5060
    - 2379
    - 2380
    - 5001
    - 7000
    - 8008

  - name: Ativando firewall da m치quina - Node Patroni
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi

