- hosts: nodesrabbitmq
  tasks:
  
  - name: Liberando a porta no firewall - Node RabbitMQ
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
    - 1883
    - 5671
    - 5672
    - 15672
    - 15675
    - 15678

  - name: Ativando firewall da m치quina - Node RabbitMQ
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi
