- hosts: nodesredis
  tasks:
  
  - name: Liberando a porta no firewall - Node Redis
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
    - 6379
    - 6380
    - 6381

  - name: Ativando firewall da m치quina - Node Redis
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi