- hosts: 'teste'

  tasks:
  - name: 'INSERINDO ROUTES NO ARQUIVO DE CONFIGURAÇÃO DE REDE'
    shell: |
      sed -i '/routes:/a \ \ \ \ \ \ \ \ - to: 10.20.30.40/22\n\ \ \ \ \ \ \ \ \ \ via: 10.100.0.50' /etc/netplan/00-installer-config.yaml

  - name: 'NETPLAN APPLY'
    shell: netplan apply

