- hosts: nodesmongo
  tasks:
  
  - name: Liberando a porta no firewall - Node Mongo
    ufw:
      rule: allow
      port: '27017'
      proto: tcp

  - name: Ativando firewall da m치quina - Node Mongo
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi

