- hosts: nodesprocapi
  tasks:
  
  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '5060'
      proto: tcp

  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '5432'
      proto: tcp

  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '27017'
      proto: tcp

  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '1024'
      proto: tcp

  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '8001'
      proto: tcp

  - name: Liberando a porta no firewall - Node Procapi
    ufw:
      rule: allow
      port: '5556'
      proto: tcp

  - name: Ativando firewall da m치quina - Node Procapi
    shell: |
            if ufw status | grep -q 'Status: active'; then
            echo "Firewall j치 est치 ativado."
            else
            echo "Ativando firewall da m치quina"
            yes | ufw enable
            ufw status
            fi